micronaut:
  application:
    name: micronautguide
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: jonas
liquibase:
  datasources:
    default:
      change-log: classpath:db/changelog/liquibase-changelog.xml
netty:
  default:
    allocator:
      max-order: 3
